server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.33.200.230:3306/vocabulary?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: yayaword608
  # 邮箱设置
  mail:
    username: 204967882@qq.com
    password: uihpfidksmmxbigh #授权码
    host: smtp.qq.com  #其他的就把qq改了就行，如 smtp.163.com
    #编码格式
    default-encoding: utf-8
    #开启加密验证
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
